---
- hosts: localhost
  gather_facts: no
  module_defaults:
          group/aws:
                  region: "us-east-2"
  tasks:
          - name: Create VPC
            ec2_vpc_net:
                    name: Module5
                    cidr_block: 10.0.0.0/16
                    tags:
                            Name: Module5
                    state: present
            register: vpc
          
          - name: debug
            debug: var=vpc

          - name: "Create Public Subnet 1"
            ec2_vpc_subnet:
                    tags:
                            Name: Module5 public1
                    vpc_id: "{{ vpc.vpc.id }}"
                    cidr: 10.0.1.0/24
                    az: us-east-2a
                    map_public: yes
                    state: present
            register: public_subnet1

          - name: "Create Public Subnet 2"
            ec2_vpc_subnet:
                    tags:
                            Name: Module5 public2
                    vpc_id: "{{ vpc.vpc.id }}"
                    cidr: 10.0.2.0/24
                    az: us-east-2b
                    map_public: yes
                    state: present
            register: public_subnet2


          - name: Create Private Subnet1
            ec2_vpc_subnet:
                    tags:
                            Name: Module5 private1
                    vpc_id: "{{ vpc.vpc.id }}"
                    cidr: 10.0.3.0/24
                    az: us-east-2c
                    map_public: yes
                    state: present
            register: private_subnet1

          - name: Create Private Subnet2
            ec2_vpc_subnet:
                    tags:
                            Name: Module5 private2
                    vpc_id: "{{ vpc.vpc.id }}"
                    cidr: 10.0.4.0/24
                    az: us-east-2b
                    state: present
            register: private_subnet2


          - name : Create Internet Gateway
            ec2_vpc_igw:
                    vpc_id: "{{ vpc.vpc.id }}"
                    tags:
                            Name: Module5 IGW
                    state: present
            register: igw

          - name: debug
            debug: var=igw

          - name: Create Public Subnet Route Table
            ec2_vpc_route_table:
                    vpc_id: "{{ vpc.vpc.id }}"
                    tags:
                            Name: Module5
                    subnets:
                            - "{{ public_subnet1.subnet.id }}"
                            - "{{ public_subnet2.subnet.id }}"

                    routes:
                            - dest: 0.0.0.0/0
                              gateway_id: "{{ igw.gateway_id }}"
                    state: present

          - name: Create NAT for Private Subnets
            ec2_vpc_nat_gateway:
                    subnet_id: "{{ private_subnet1.subnet.id }}"
                    if_exist_do_not_create: true
                    state: present
                    wait: yes
            register: nat

          - name: debug
            debug: var=nat

          - name: Create Application Target Group
            elb_target_group:
                    name: Module5tg
                    protocol: tcp
                    port: 80
                    health_check_protocol: http
                    stickiness_enabled: no
                    stickiness_type: source_ip
                    vpc_id: "{{ vpc.vpc.id }}"
                    state: present

          - name: Create Network Load Balancer
            elb_network_lb:
                    name: mod5-nlb
                    subnets:
                            - "{{ public_subnet1.subnet.id }}"
                            - "{{ public_subnet2.subnet.id }}"
                    listeners:
                            - Protocol: TCP
                              Port: 443
                              DefaultActions:
                                      - Type: forward
                                        TargetGroupName: Module5tg
                    state: present
            register: nlb

          - name: Debuging route53
            route53_info:
                    query: hosted_zone
            register: hosted_zones
          - debug: var=hosted_zones

          - name: Debuging route53
            route53_info:
                    query: record_sets
                    hosted_zone_id: "{{ hosted_zones.HostedZones[0].Id }}"
            register: records
          - debug: var=records


          - name: "Disassociate current NLB with domain via Route 53"
            route53:
                    state: absent
                    record: novawoodworks.co
                    type: A
                    value: "{{ records.ResourceRecordSets[0].AliasTarget.DNSName }}"
                    hosted_zone_id: "{{ hosted_zones.HostedZones[0].Id }}"

          - name: "Associate new NLB with domain via Route 53"
            route53:
                    state: present
                    record: novawoodworks.co
                    type: A
                    value: "{{ nlb.dns_name }}"
                    alias: True
                    alias_hosted_zone_id: "{{ hosted_zones.HostedZones[0].Id }}"

                    
          - name: Create public web Security Group
            ec2_group:
                    name: Module5-dev-sg
                    description: Development security group
                    vpc_id: "{{ vpc.vpc.id }}"
                    rules:
                            - proto: tcp
                              ports:
                                      - 22
                                      - 80
                                      - 443
                              cidr_ip: 0.0.0.0/0
                              rule_desc: allow all to ports 22 and 80
                    state: present
            register: nginxsg

          - name: Create private jetty Security Group
            ec2_group:
                    name: Module5-app-sg
                    description: Application security group
                    vpc_id: "{{ vpc.vpc.id }}"
                    rules:
                            - proto: tcp
                              ports:
                                      - 22
                              cird_ip: 0.0.0.0/0
                            - proto: tcp
                              ports:
                                      - 5555
                                      - 443
                              cidr_ip: 10.0.0.0/16
                              rule_desc: allow vpc in on 5555 and 443
                    state: present
            register: jettysg


          - name: Create postgres client security group
            ec2_group:
                    name: image-gallery-postgres-tag
                    description: Postgres client security group
                    vpc_id: "{{ vpc.vpc.id }}"
                    rules:
                            - proto: tcp
                              ports:
                                      - 5432
                              rule_desc: allows access to postgres
                    rules_egress:
                            - proto: tcp
                              ports:
                                      - 5432
                              rule_desc: allows inbound from postgres
                    state: present
            register: postgrestag

          - name: Create postgres server security group
            ec2_group:
                    name: image-gallery-postgres
                    description: Postgres service security group
                    vpc_id: "{{ vpc.vpc.id }}"
                    rules:
                            - proto: tcp
                              ports:
                                      - 5432
                              group_id: "{{ postgrestag.group_id }}"
                              rule_desc:
                    rules_egress:
                            - proto: tcp
                              ports:
                                      - 5432
                              rule_desc: allow sg tagged objects into postgres
                    state: present
            register: postgressg

          - name: Update postgres client security group
            ec2_group:
                    name: image-gallery-postgres-tag
                    description: Postgres client security group
                    vpc_id: "{{ vpc.vpc.id }}"
                    rules:
                            - proto: tcp
                              ports:
                                      - 5432
                              group_id: "{{ postgressg.group_id }}"
                              rule_desc: allows access to postgres
                    state: present

