---
- hosts: localhost
  gather_facts: no
  module_defaults:
          group/aws:
                  region: "us-east-2"
  tasks:
        - rds:
                command: create
                instance_name: Module5-image-gallery
                db_engine: postgres
                size: 20
                instance_type: db.t2.micro
                username: image_gallery
                password: randomb4awsSMkicksin
                security_groups: "{{ postgressg.group_id }}"
                tags:
                        Name: image-gallery
                        Module: 5
