---
- hosts: localhost
  gather_facts: no
  vars:
          ami_id: "ami-026dea5602e368e96"
  module_defaults:
          group/aws:
                  region: "us-east-2"
  tasks:
          - name: Provision Public web ec2
            ec2:
                    key_name: auburn
                    group: Module5-dev-sg
                    instance_type: t3.nano
                    image: "{{ ami_id }}"
                    instance_tags:
                            Name: Module5 web
                            Module: 5
                    wait: yes
                    vpc_subnet_id: "{{ public_subnet.subnet.id }}"
                    assign_public_ip: yes
                    exact_count: 2
                    count_tag:
                            Name: Module5 web
                            Module: 5

