---
- hosts: localhost
  gather_facts: no
  vars:
          ami_id: "ami-026dea5602e368e96"
          iam_role: ig-server-role

  module_defaults:
          group/aws:
                  region: "us-east-2"
  tasks:
        - name: Create nginx web launch template
          ec2_launch_template:
                name: "m5nginx"
                image_id: "{{ ami_id }}"
                key_name: auburn
                instance_type: t3.nano
                security_group_ids:
                        - "{{ nginxsg.group_id }}"
                iam_instance_profile: "{{ iam_role }}"
                user_data: "{{ lookup('file', '../ec2-scripts/nginx-userdata.sh') | b64encode }}"
        
        - name: Create jetty app launch template
          ec2_launch_template:
                name: "m5prod"
                image_id: "{{ ami_id }}"
                key_name: auburn
                instance_type: t3.micro
                security_group_ids:
                        - "{{ postgrestag.group_id }}"
                        - "{{ jettysg.group_id }}"
                iam_instance_profile: "{{ iam_role }}"
                user_data: "{{ lookup('file', '../ec2-scripts/prod-userdata.sh') | b64encode }}"

