---
- hosts: localhost
  gather_facts: no
  module_defaults:
          group/aws:
                  region: "us-east-2"
  tasks:
          - s3_bucket:
                  name: edu.au.cc.jzw.image-gallery
                  state: present

          - s3_bucket:
                  name: edu.au.cc.jzw.image-gallery-config
                  state: present

